apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: archive
  labels:
    app: firstMS
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          name: archive
        spec:
          restartPolicy: Never
          containers:
            - name: cron
              image: mysql:8.0
              command:
                - /bin/sh
                - -c
                - mysql -h database --user=root --password=$MYSQL_ROOT_PASSWORD --database=$MYSQL_DATABASE --execute="update Link set archived = '1' where DATEDIFF( NOW( ) ,  created ) >=7"
              env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
                - name: MYSQL_DATABASE
                  value: "mslinks"
  schedule: "* * * * *"

