apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-ms
  labels:
    app: firstMS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstMS
  template:
    metadata:
      labels:
        app: firstMS
    spec:
      containers:
        - name: database
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: "mslinks"

          ports:
            - containerPort: 3306

        - name: rabbitmq
          image: rabbitmq
          ports:
            - containerPort: 5672

        - name: uploader
          image: darthsett/csv-uploader
          ports:
            - containerPort: 4000

        - name: scraper
          image: darthsett/product-scraper
          ports:
            - containerPort: 1000
