version : 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          -GO111MODULE: "ON"
    working_directory: ~/go/src/github.com/FirstMicroService
    steps:
      - checkout
      - run: go mod verify
      - run: go test ./ScraperService/Scraper

  printer:
    machine: true
    steps:
      - run: echo "Running from Printer"
workflows:
  version: 2
  build_and_printer:
    jobs:
      - build
      - printer