version : 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          -GO111MODULE: "ON"
    working_directory: ~/go/src/github.com/FirstMicroService
    steps:
      - checkout
      - run: go mod verify
      - run: go test ./ScraperService/Scraper

  deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true # (3)
      - run: docker login --username=darthsett --password=$DOCKER_PASS
      - run: docker-compose build
      - run: docker image ls
#     - run: docker tag csv-uploader darthsett/csv-uploader:latest
#     - run: docker tag product-scraper darthsett/product-scraper:latest
      - run: docker push darthsett/csv-uploader
      - run: docker push darthsett/product-scraper
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
